### ISSUE TITLE
AI shell death

### ISSUE THREAD

**Issue by nednaZ** [Monkestation/MonkeStation#395] opened 2022-05-27 17:16 UTC
An non-malf AI that is piloting a mech will actually die entirely if their mech is destroyed, no way to recover them.

The mech wreckage also holds a lot of references to the dead AI, likely garbage collection issue

**Comment by dwasint** [comment] 2023-03-11 07:30
for some reason this is intended behaviour of the mech. Closing as its not an issue and putting this on the list of features to add

**Closed by dwasint** 2023-03-11 07:30 UTC
